### ISSUE TITLE
Creation datetime changes when re-generating existing elements

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/librepcb-parts-generator#15]
The "created" node in the generated s-expression files changes every time when re-generating existing elements, so Git always shows all generated files as modified.

Should we just store the creation datetime in the CSV file?

**Comment by dbrgn** [comment]
We could do that.

Do library elements have a concept of "last updated" time?

**Comment by ubruhin** [comment]
> Do library elements have a concept of "last updated" time?

They had, but I removed it because it's annoying when using version control systems :wink:
