### ISSUE TITLE
License

### ISSUE THREAD

**Issue by HBadertscher** [LibrePCB/librepcb-parts-generator#26]
Currently, this repository and the contained scripts do not have any license. Is this on purpose? Should we license them under an open-source license? If so, what license do we choose? E.g. CC-0 like the generated parts or GPL like LibrePCB or even something else?

**Comment by dbrgn** [comment]
Ah, good point. No, that is not on purpose!

CC-0 is not really a software license, but we can put it under the MIT license?

**Comment by HBadertscher** [comment]
That's true. It looks like so far only you commited to this repo, so I guess technically, it is only up to you to decide.

The main decision is, if you want to allow for commercial usage or not. Personally, I think there is little harm in using the MIT license. Worst case: somebody creates a derivative of the parts generator and starts selling the generated packages or uses the generators for their proprietary EDA-tool... ¯\\\_(ツ)\_/¯

What is your opinion @ubruhin ?

**Comment by dbrgn** [comment]
The generator is quite hacky and very LibrePCB specific, so if someone manages to re-use the code I don't care :slightly_smiling_face:

**Comment by ubruhin** [comment]
MIT sounds reasonable :+1: :)
