### ISSUE TITLE
generate_connectors: Footprint variants

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/librepcb-parts-generator#4]
- default -> Hand soldering, oval pads
- compact -> Round pads

Not sure if there should be a labelled version too... The question is, what rotation should the labels have?

**Comment by rnestler** [comment]
> default -> Hand soldering, oval pads

Why should the default be optimized for hand soldering? Hand soldering is a special case isn't it?

**Comment by dbrgn** [comment]
I think the oval pads might also be useful in manufacturing with wave soldering, right? They're also more robust: https://electronics.stackexchange.com/questions/173365/purpose-of-oval-oblong-pcb-through-hole-pads

I'm not even sure if we should add round versions at all.

**Comment by rnestler** [comment]
> I'm not even sure if we should add round versions at all.

When the only advantage is compactness it may not be worth it.

**Comment by dbrgn** [comment]
Let's close this until someone comes up with a real need.
