### ISSUE TITLE
Move this repository to LibrePCB-libraries organization?

### ISSUE THREAD

**Issue by rnestler** [LibrePCB/librepcb-parts-generator#40]
Since it is more related to the libraries, should we move it? I searched for it today and searched first in the libraries orga, but that is just anecdotal :wink:

**Comment by dbrgn** [comment]
Would be OK for me.

**Comment by ubruhin** [comment]
I wouldn't do that - this is not a library, but source code. Initially the API server even scanned the LibrePCB-Libraries organization and considered every repository as a library. That has changed in the meantime, but it might still be useful in future to have libraries strictly separated from code.

If there is a good reason to change it, I'm open to reconsider it - but at this time I think it has no advantage to move the repo. Feel free to reopen this issue if you disagree :)

**Comment by rnestler** [comment]
Ah right. It is probably good to have only libraries and not stuff related to libraries in the LibrePCB-Libraries organization.
