### ISSUE TITLE
 generate_connectors: Hole diameter

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/librepcb-parts-generator#5]
Should we create packages in the default library for both rather common diameters of 0.8mm and 1mm? Or even 0.8/0.9/1mm?

RFC @ubruhin

**Comment by ubruhin** [comment]
According datasheet ;)

**Comment by dbrgn** [comment]
I'm talking about a default set of connector footprints that can be used by the concrete devices :)

**Comment by dbrgn** [comment]
Seems that 1mm seems fine according to some datasheets.
